# Generated by Django 6.0.3 on 2026-03-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
